feat:home, layout 공동작업
FlexGym/Flex_Gym pull request #49
Opened 2023-06-12 09:05 UTC by tkdtn4657

home.html, layout UI공동작업 내용입니다

2023-06-12 10:53 UTC, dw2023 approved these changes
👍

2023-06-12 12:26 UTC, leebuwon requested changes
static에 images폴더 삭제하고 진행하면 더 좋을 것 같습니다.

2023-06-13 00:00 UTC, tkdtn4657 commented
> static에 images폴더 삭제하고 진행하면 더 좋을 것 같습니다.

이미지 삭제하고 푸쉬했습니다 확인 부탁드려요

2023-06-13 00:06 UTC, leebuwon approved these changes
감사합니다!!

2023-06-13 00:14 UTC, merged